### PR TITLE
[wip] Browser fixes

### PR DESCRIPTION
**Pull request by stagas**
**WIP do not merge**

This PR solves a few issues regarding the previous PR #1 :

- AudioContext starting after user gesture needed by browser policy.
- Remove TypedArray exports and remove loader dependency. We include only what we use (a couple of functions).

Issues:

- The recent dependency on WASI breaks this because it expects interfaces that don't exist in the browser. Is it necessary to include a systems programming library for the audio processing unit? That would most likely make the AudioWorklet incompatible and we'd need a separate build to run the plugin in WebAudio, one that includes `wasi` and one that doesn't. How do you suggest we get around this issue?

### CODE REVIEW

**Comment by lucianoiam** [comment]
> * The recent dependency on WASI breaks this because it expects interfaces that don't exist in the browser. Is it necessary to include a systems programming library for the audio processing unit? That would most likely make the AudioWorklet incompatible and we'd need a separate build to run the plugin in WebAudio, one that includes `wasi` and one that doesn't. How do you suggest we get around this issue?

To be honest I added WASI to benefit from the family of log() functions and thought it could be also useful for reading/writing files on disk. The `WasmHostPlugin` part actually does more than running DSP and AssemblyScript without WASI is very limited compared to C++. But I see the point and maybe it is a better idea to make WASI optional and disabled by default, as its use cases are probably unusual.

**Comment by stagas** [comment]
I see the benefit of having access to system APIs as well. Hmm, I think it should be up to the user to decide whether to opt into that because then it defeats part of the "portable" nature of Wasm and the easiness of running / developing / demoing your plugins in browser context. There exists a [polyfill](https://wasi.dev/polyfill/polyfill.js) though and we could use that just wanted to make sure what is your direction or if you have other ideas before jumping into that.

**Comment by lucianoiam** [comment]
DPF provides some features optionally (see DistrhoPluginInfo.h). It makes sense to make WASI optional for the greatest flexibility. Then the plugin author can decide to switch it on/off and apply polyfills if needed on a project basis.

**Comment by lucianoiam** [comment]
As discussed all  browser integrations will be implemented within a custom plugin at https://github.com/kstrukt/hiphop-shell-plugin

**Pull request closed without merging**
